#:schema node_modules/wrangler/config-schema.json
name = "bolt-diy"
main = "worker/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
send_metrics = false
assets = { directory = "./build/client" }

[vars]
NODE_ENV = "production"
